
```{r setup, include=FALSE}
library(tidyverse)
library(rsample)
library(here)
library(mirt)
library(quantregGrowth)
theme_set(theme_classic())
```

```{r load_data}
survey_raw <- read_rds(here("data-clean/survey_raw.rds"))

responses_long <- read_rds(here("data-clean/responses_long.rds"))
responses_wide <- read_rds(here("data-clean/responses_wide.rds"))

milestones <- read_rds(here("data-clean/milestones.rds"))
areas <- read_rds(here("data-clean/areas.rds"))
```

```{r remove_ages}
# remove ages <= 1

by_age <-
	responses_long %>%
	group_by(id) %>%
	summarize(
		age = age[1],
		response = sum(response)
	) %>%
	filter(age > 1)

responses_wide <- responses_wide %>% filter(id %in% by_age$id)
responses_long <- responses_long %>% filter(age > 1)
```

```{r}
source("~/Desktop/cvirt/R/helpers.R")

# this does stratified-by-person masking
mask_item_response_data <- function(data, percent_mask){
	notna <- which(!is.na(as.numeric(data)))
	makena <- sample(notna, round(percent_mask * length(notna)))
	data[makena] <- NA
	data
}

# now let's make train and test data
train <- 
	select(responses_wide, -1) %>% 
	apply(1, mask_item_response_data, 0.3) %>% 
	t()
test <- select(responses_wide, -1) %>% as.matrix()
test[!is.na(select(responses_wide, -1)) & !is.na(train)] <- NA
```

```{r}
model_table <-
	crossing(
		n_fact = 1:3,
		a_sd = c(0.2, 0.5),
		all = c(TRUE, FALSE),
		d_sd = c(0.5, 2)
	) %>%
	mutate(
		string = pmap_chr(., build_model_string, ncol(train)),
		method = "QMCEM" # removed EM here 
	)
```

```{r}
# fit models
models_bayes <-
	model_table %>%
	mutate(
		in_model =
			map2(
				string,
				method,
				~ mirt(train, mirt.model(.x), method = .y, technical = list(NCYCLES = 200))
			),
		fscores = map2(in_model, method, ~ fscores(.x, QMC = .y == "QMCEM", rotate = "none")),
		p = map2(in_model, fscores, get_p),
		eval = p %>% map(evaluate_p, train, test)
	)

# see what we got
models_bayes %>%
	select(-in_model, -fscores, -p) %>%
	unnest_wider(eval) %>%
	View()

save.image("cogsci-revisions-priors.Rdata")
```

